# Generated by Django 4.0.3 on 2022-03-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcmeWebhookMessage',
        ),
    ]
