# Generated by Django 3.2.13 on 2022-05-16 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import matchat.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_com', models.CharField(max_length=20)),
                ('card_num1', models.CharField(max_length=20)),
                ('card_num2', models.CharField(max_length=20)),
                ('card_num3', models.CharField(max_length=20)),
                ('card_num4', models.CharField(max_length=20)),
                ('cvc_num', models.CharField(max_length=20)),
                ('dead_year', models.CharField(max_length=20)),
                ('dead_month', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('use_period', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('content', models.TextField(null=True)),
                ('create_date', models.DateTimeField()),
                ('state', models.CharField(default='0', max_length=1)),
                ('key', models.IntegerField(null=True)),
                ('place', models.CharField(default='이대역', max_length=10)),
                ('kiosk_photo', models.CharField(blank=True, max_length=2090, null=True)),
                ('kiosk_result', models.CharField(default='none', max_length=100)),
                ('web_result', models.CharField(default='none', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=matchat.models.directory_path)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matchat.product')),
            ],
        ),
    ]
