# Generated by Django 3.1.3 on 2022-02-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='create_data',
            new_name='create_date',
        ),
    ]
