# Generated by Django 3.1.3 on 2022-02-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchat', '0002_auto_20220216_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
