# Generated by Django 3.1.3 on 2022-02-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchat', '0006_product_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
