# Generated by Django 3.1.3 on 2022-02-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchat', '0007_product_modify_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
