# Generated by Django 3.1.3 on 2022-02-22 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchat', '0011_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp',
        ),
    ]
