# Generated by Django 3.1.3 on 2022-02-23 09:18

from django.db import migrations, models
import matchat.models


class Migration(migrations.Migration):

    dependencies = [
        ('matchat', '0012_delete_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=matchat.models.directory_path),
        ),
    ]
