# Generated by Django 3.1.3 on 2022-02-23 09:33

from django.db import migrations, models
import django.db.models.deletion
import matchat.models


class Migration(migrations.Migration):

    dependencies = [
        ('matchat', '0013_auto_20220223_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=matchat.models.directory_path)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matchat.product')),
            ],
        ),
    ]
