# Generated by Django 3.1.3 on 2022-02-23 13:18

from django.db import migrations, models
import django.db.models.deletion
import matchat.models


class Migration(migrations.Migration):

    dependencies = [
        ('matchat', '0014_auto_20220223_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_com', models.CharField(max_length=20)),
                ('card_num1', models.CharField(max_length=20)),
                ('card_num2', models.CharField(max_length=20)),
                ('card_num3', models.CharField(max_length=20)),
                ('card_num4', models.CharField(max_length=20)),
                ('cvc_num', models.CharField(max_length=20)),
                ('dead_year', models.CharField(max_length=20)),
                ('dead_month', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kiosk_Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=matchat.models.directory_path)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matchat.product')),
            ],
        ),
    ]
