# Generated by Django 3.1.3 on 2022-02-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchat', '0015_credit_info_kiosk_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='key',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lock_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
