# Generated by Django 3.1.3 on 2022-02-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchat', '0018_remove_product_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='key',
            field=models.IntegerField(null=True),
        ),
    ]
