# Generated by Django 3.1.3 on 2022-03-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchat', '0019_product_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
