# Generated by Django 3.1.3 on 2022-03-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchat', '0020_auto_20220302_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='place',
            field=models.CharField(default='이대역', max_length=10),
        ),
    ]
