# Generated by Django 3.1.3 on 2022-03-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchat', '0021_product_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosk_photo',
            name='result',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='result',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
