# Generated by Django 3.1.3 on 2022-04-13 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matchat', '0022_auto_20220322_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='result',
        ),
        migrations.AddField(
            model_name='product',
            name='kiosk_photo',
            field=models.CharField(blank=True, max_length=2090, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='kiosk_result',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Kiosk_Photo',
        ),
    ]
