# Generated by Django 4.0.3 on 2022-04-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchat', '0023_auto_20220414_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='modify_date',
        ),
    ]
